# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Absolute complexity mark A by xenon

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check complexity with xenon
      run: |
        python -m pip install --upgrade pip xenon
        xenon --max-absolute A .